---
# aws:
#   access_key_id: whatever
#   secret_access_key: whatever
#   s3:
#     bucket: mybucket
#     bucket_path: mybucket_path
#   sns:
#     arn: asdfasdfasdfasdf
# mysql:
#   host: localhost
#   username: root
#   password:
#   port: 
#   database: 
local_pdfs_path: pdfs
csv: 'moving_summons_stats.csv'
