source "https://rubygems.org"

gem 'tabula-extractor'
gem 'aws-sdk', '>= 2.0.6.pre'
gem "upton"
gem 'aws-sdk-v1'
gem 's3-publisher'
gem "activerecord"
gem "activerecord-jdbcmysql-adapter"
gem 'activerecord-jdbc-adapter', '~> 1.3', platform: :jruby

